apiVersion: apps/v1
kind: Deployment

metadata:
  name: salary-management

spec:
  replicas: 3

  selector:
    matchLabels:
      app: salary-management

  template:
    metadata:
      labels:
        app: salary-management

    spec:
      containers:
      - name: salary-management
        image: salary-management:latest
        ports:
        - containerPort: 8000
